# Generated by Django 4.2.4 on 2023-08-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="search", options={"verbose_name_plural": "Searches"},
        ),
    ]
